services:
  runner:
    image: johnwid92/actions-image:latest
    restart: always
    environment:
      - REPO=${GH_REPO}
      - TOKEN=${GH_PAT}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G