services:
  runner:
    image: johnwid92/actions-image:latest
    # restart: always
    environment:
      - REPO=${GH_REPO}
      - TOKEN=${GH_PAT}
    volumes:
      - ./start.sh:/home/docker/start.sh
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G