name: Simple Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a simple script
      run: echo "Hello, GitHub Actions!"